name: Generate sitemap

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sitemap.xml
        uses: cicirello/generate-sitemap@v1
        with:
          base-url: https://www.controldeldolorsv.com

      - name: Commit and push sitemap.xml
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add sitemap.xml
          git commit -m "Add/update sitemap.xml" || echo "No changes"
          git push
